/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bca9balltableassigner;

import java.awt.Component;
import java.awt.HeadlessException;
import java.io.BufferedWriter;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author c_dra
 */
public class Bca9BallTableAssignerUI extends javax.swing.JFrame {

    private static File lastDirectory = new File(System.getProperty("user.home")); // Default to user's home directory
    private JFileChooser fileChooser;

    /**
     * Creates new form Bca9BallTableAssignerUI
     */
    public Bca9BallTableAssignerUI() {
        initComponents();
        try {
            fileChooser = new JFileChooser();
            File jarFile = new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());
            File jarDirectory = jarFile.getParentFile();
            fileChooser.setCurrentDirectory(jarDirectory);
        } catch (URISyntaxException use) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCsvLeagueSchedule = new javax.swing.JPanel();
        txtCsvLeagueSchedule = new javax.swing.JTextField();
        btnBrowseCsvLeagueSchedule = new javax.swing.JButton();
        btnGenerateTableAssignments = new javax.swing.JButton();
        scrPnlTableAssignment = new javax.swing.JScrollPane();
        tblTableAssignment = new javax.swing.JTable();
        btnExportTableAssignment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BCA League Table Assigner");

        pnCsvLeagueSchedule.setBorder(javax.swing.BorderFactory.createTitledBorder("CSV League Schedule"));

        txtCsvLeagueSchedule.setEditable(false);

        btnBrowseCsvLeagueSchedule.setText("Browse");
        btnBrowseCsvLeagueSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseCsvLeagueScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCsvLeagueScheduleLayout = new javax.swing.GroupLayout(pnCsvLeagueSchedule);
        pnCsvLeagueSchedule.setLayout(pnCsvLeagueScheduleLayout);
        pnCsvLeagueScheduleLayout.setHorizontalGroup(
            pnCsvLeagueScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCsvLeagueScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCsvLeagueSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrowseCsvLeagueSchedule)
                .addContainerGap())
        );
        pnCsvLeagueScheduleLayout.setVerticalGroup(
            pnCsvLeagueScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCsvLeagueScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCsvLeagueScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCsvLeagueSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseCsvLeagueSchedule))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerateTableAssignments.setText("Generate Table Assignments");
        btnGenerateTableAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTableAssignmentsActionPerformed(evt);
            }
        });

        tblTableAssignment.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        tblTableAssignment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Week", "1", "2", "3", "4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTableAssignment.setShowGrid(true);
        scrPnlTableAssignment.setViewportView(tblTableAssignment);

        btnExportTableAssignment.setText("Export Table Assignments");
        btnExportTableAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportTableAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPnlTableAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(pnCsvLeagueSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExportTableAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateTableAssignments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCsvLeagueSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerateTableAssignments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPnlTableAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportTableAssignment)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseCsvLeagueScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseCsvLeagueScheduleActionPerformed
        fileChooser.setDialogTitle("Select League CSV To Load");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV File", "csv");
        fileChooser.setFileFilter(filter);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            txtCsvLeagueSchedule.setText(fileChooser.getSelectedFile().getAbsolutePath());
            lastDirectory = fileChooser.getSelectedFile().getParentFile();
        }
    }//GEN-LAST:event_btnBrowseCsvLeagueScheduleActionPerformed

    private void btnGenerateTableAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTableAssignmentsActionPerformed
        if (txtCsvLeagueSchedule.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a CSV League Schedule", "Information", JOptionPane.INFORMATION_MESSAGE);
            btnBrowseCsvLeagueSchedule.requestFocusInWindow();
            return;
        }

        Schedule leagueSchedule = new Schedule(txtCsvLeagueSchedule.getText());
        if (!leagueSchedule.validateSchedule()) {
            JOptionPane.showMessageDialog(this,
                    String.format("""
                                  %s\r
                                  is not a valid CSV League Schedule.\r\n
                                  The expected format is:\r\n
                                  #,# @ #,# @ #,etc...
                                  """,
                            txtCsvLeagueSchedule.getText()),
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        leagueSchedule.processSchedule();
        TableAssigner tableAssigner = new TableAssigner(leagueSchedule);
        tblTableAssignment.setModel(tableAssigner.getTableAssignments());
        tblTableAssignment.getTableHeader().setDefaultRenderer(new TableHeaderBorderRenderer());

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblTableAssignment.getColumnModel().getColumnCount(); i++) {
            tblTableAssignment.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        autoResizeColumns(tblTableAssignment);
    }//GEN-LAST:event_btnGenerateTableAssignmentsActionPerformed

    private void btnExportTableAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportTableAssignmentActionPerformed
        if (tblTableAssignment.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "There are no table assignments to export!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            int exportOption;
            int overwriteOption = JOptionPane.YES_OPTION;
            String filePath = "";
            do {
                exportOption = openExportTableAssignmentsDialog();
                if (exportOption != JFileChooser.APPROVE_OPTION) {
                    return;
                }

                filePath = fileChooser.getSelectedFile().getAbsoluteFile().getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".csv")) {
                    filePath += ".csv";
                }

                File selectedFile = new File(filePath);
                if (selectedFile.exists()) {
                    overwriteOption = JOptionPane.showConfirmDialog(this,
                            "File already exists. Do you want to overwrite it?",
                            "Overwrite Confirmation",
                            JOptionPane.YES_NO_OPTION);
                }
            } while (exportOption == JFileChooser.APPROVE_OPTION && overwriteOption != JOptionPane.YES_OPTION);

            TableModel model = tblTableAssignment.getModel();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {

                // Write header row
                for (int col = 0; col < model.getColumnCount(); col++) {
                    writer.write(model.getColumnName(col));
                    if (col < model.getColumnCount() - 1) {
                        writer.write(",");
                    }
                }
                writer.newLine();

                // Write data rows
                for (int row = 0; row < model.getRowCount(); row++) {
                    for (int col = 0; col < model.getColumnCount(); col++) {
                        Object value = model.getValueAt(row, col);
                        writer.write(value == null ? "" : value.toString());
                        if (col < model.getColumnCount() - 1) {
                            writer.write(",");
                        }
                    }
                    writer.newLine();
                }
            }
            JOptionPane.showMessageDialog(this, "Export Complete!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | IOException e) {

        }
    }//GEN-LAST:event_btnExportTableAssignmentActionPerformed

    private void autoResizeColumns(JTable table) {
        for (int column = 0; column < table.getColumnCount(); column++) {
            int maxWidth = 0;
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component component = table.prepareRenderer(renderer, row, column);
                maxWidth = Math.max(maxWidth, component.getPreferredSize().width);
            }
            table.getColumnModel().getColumn(column).setPreferredWidth(maxWidth);
        }
    }

    private int openExportTableAssignmentsDialog() {
        fileChooser.setDialogTitle("Export Table Assignments");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV File", "csv");
        fileChooser.setCurrentDirectory(lastDirectory);
        fileChooser.setFileFilter(filter);
        return fileChooser.showOpenDialog(this);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bca9BallTableAssignerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bca9BallTableAssignerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bca9BallTableAssignerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bca9BallTableAssignerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bca9BallTableAssignerUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseCsvLeagueSchedule;
    private javax.swing.JButton btnExportTableAssignment;
    private javax.swing.JButton btnGenerateTableAssignments;
    private javax.swing.JPanel pnCsvLeagueSchedule;
    private javax.swing.JScrollPane scrPnlTableAssignment;
    private javax.swing.JTable tblTableAssignment;
    private javax.swing.JTextField txtCsvLeagueSchedule;
    // End of variables declaration//GEN-END:variables
}
